export enum ErrorMessage {
  ANIMAL_NOT_FOUND = 'ANIMAL_NOT_FOUND',
  ANIMAL_NOT_AVAILABLE = 'ANIMAL_NOT_AVAILABLE',
  INQUERY_NOT_FOUND = 'INQUERY_NOT_FOUND',
  INQUERY_NOT_PENDING = 'INQUERY_NOT_PENDING',
  INQUERY_ALREADY_EXISTS = 'INQUERY_ALREADY_EXISTS',
  INQUERY_PENDING = 'INQUERY_PENDING',
  INQUERY_FINISHED = 'INQUERY_FINISHED',
  OWN_AUTHOR = 'OWN_AUTHOR',
}
