export enum ErrorMessage {
  ANIMAL_NOT_FOUND = 'ANIMAL_NOT_FOUND',
  ANIMAL_NOT_PENDING = 'ANIMAL_NOT_PENDING',
  ANIMAL_ALREADY_ADOPTED = ' ANIMAL_ALREADY_ADOPTED',
  USER_NOT_INQUERIER = 'USER_NOT_INQUERIER',
}
